---
- hosts: nodes
  remote_user: ec2-user
  become: yes
  become_method: sudo
  vars:
    var_node: /tmp
  tasks:
    - include: tasks/prerequisites.yaml
    - include: tasks/mongodb.yaml
    - include: tasks/nodejs.yaml
    - include: tasks/pushpin.yaml
