- name: MongoDB Ensure repo file existence
  copy:
    content: ""
    dest: /etc/yum.repos.d/mongodb-org-4.2.repo
    force: no

- name: MongoDB Add Repo
  yum_repository:
    name: MongoDB-Repository
    description: MongoDB Repository
    reposdir: /etc/yum.repos.d
    file: /etc/yum.repos.d/mongodb-org-4.2
    baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.2/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present

- name: MongoDB Install MongoDB
  yum:
    name: mongodb-org
    state: present
    update_cache: yes
    lock_timeout: 180

- name: MongoDB Running State
  service:
    name: mongod
    state: started
