- name: Ensure EPEL
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    lock_timeout: 180

- name: Node.js Get Script
  uri:
    url: https://rpm.nodesource.com/setup_12.x

- name: Node.js Install node.js
  yum: 
    name: ['gcc-c++', 'nodejs']
    lock_timeout: 180

- name: Node.js Install Express.js
  npm:
    name: express
    global: yes
