- name: Ensure EPEL
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    lock_timeout: 180

- name: Node.js Get Script
  raw: curl https://rpm.nodesource.com/setup_12.x | bash -

- name: Install Node.JS
  yum:
    name: ['gcc-c++', 'make', 'nodejs']
    lock_timeout: 180
